export const indiaStatesAndCities = {
  'Andhra Pradesh': ['Visakhapatnam','Vijayawada','Guntur','Tirupati','Nellore','Kurnool','Rajahmundry','Kadapa','Kakinada','Anantapur','Eluru','Ongole'],
  'Telangana': ['Hyderabad','Warangal','Nizamabad','Karimnagar','Khammam','Mahbubnagar','Nalgonda','Adilabad','Suryapet','Siddipet','Ramagundam','Bhongir'],
  'Tamil Nadu': ['Chennai','Coimbatore','Madurai','Trichy','Salem','Tirunelveli','Tiruppur','Erode','Vellore','Thoothukudi','Dindigul','Thanjavur'],
  'Karnataka': ['Bengaluru','Mysuru','Hubli','Mangaluru','Belagavi','Kalaburagi','Ballari','Davangere','Shivamogga','Tumakuru','Raichur','Udupi'],
  'Maharashtra': ['Mumbai','Pune','Nagpur','Nashik','Aurangabad','Solapur','Amravati','Kolhapur','Navi Mumbai','Thane','Sangli','Chandrapur'],
  'Delhi': ['New Delhi','North Delhi','South Delhi','East Delhi','West Delhi','Central Delhi','Dwarka','Rohini'],
  'Gujarat': ['Ahmedabad','Surat','Vadodara','Rajkot','Bhavnagar','Jamnagar','Gandhinagar','Junagadh','Anand','Navsari'],
  'Rajasthan': ['Jaipur','Jodhpur','Udaipur','Kota','Bikaner','Ajmer','Alwar','Bharatpur','Sri Ganganagar','Sikar'],
  'Uttar Pradesh': ['Lucknow','Kanpur','Agra','Varanasi','Prayagraj','Ghaziabad','Noida','Meerut','Bareilly','Aligarh','Gorakhpur','Jhansi'],
  'West Bengal': ['Kolkata','Howrah','Durgapur','Asansol','Siliguri','Berhampore','Bardhaman','Haldia'],
  'Kerala': ['Thiruvananthapuram','Kochi','Kozhikode','Thrissur','Kannur','Kollam','Palakkad','Alappuzha','Kottayam'],
  'Punjab': ['Ludhiana','Amritsar','Chandigarh','Jalandhar','Patiala','Bathinda','Pathankot','Mohali'],
  'Haryana': ['Gurugram','Faridabad','Chandigarh','Rohtak','Hisar','Panipat','Ambala','Karnal'],
  'Madhya Pradesh': ['Bhopal','Indore','Gwalior','Jabalpur','Ujjain','Sagar','Ratlam','Rewa'],
  'Bihar': ['Patna','Gaya','Bhagalpur','Muzaffarpur','Purnia','Darbhanga','Bihar Sharif'],
  'Odisha': ['Bhubaneswar','Cuttack','Rourkela','Berhampur','Sambalpur','Puri','Balasore'],
  'Jharkhand': ['Ranchi','Jamshedpur','Dhanbad','Bokaro','Hazaribagh','Deoghar'],
  'Assam': ['Guwahati','Silchar','Dibrugarh','Jorhat','Nagaon','Tinsukia'],
  'Himachal Pradesh': ['Shimla','Solan','Dharamsala','Mandi','Kullu','Una'],
  'Uttarakhand': ['Dehradun','Haridwar','Roorkee','Haldwani','Rishikesh','Nainital'],
  'Goa': ['Panaji','Margao','Vasco da Gama','Mapusa','Ponda'],
  'Chhattisgarh': ['Raipur','Bhilai','Bilaspur','Korba','Durg','Raigarh'],
};

export const timeSlots = [
  '11:00 AM – 12:00 PM',
  '12:00 PM – 1:00 PM',
  '1:00 PM – 2:00 PM',
  '2:00 PM – 3:00 PM',
  '6:00 PM – 7:00 PM',
  '7:00 PM – 8:00 PM',
  '8:00 PM – 9:00 PM',
  '9:00 PM – 10:00 PM',
];
